miaas/urls.py
__author__ = 'hanter'

from django.conf.urls import url
from . import views, apis

app_name = 'miaas'
urlpatterns = [
    # url(r'^$', views.main_page, name='main'),
    url(r'^$', views.index_page, name='index'),
    url(r'^main$', views.main_page, name='main'),
    # url(r'^main2$', views.main2_page, name='main2'),
    # url(r'^$', views.IndexView.as_view(), name='index'),

    url(r'^signin$', views.main_page, name='signin'),
    # url(r'^signin$', views.signin_page, name='signin'),
    url(r'^contact_us$', views.contact_us_page, name='contact_us'),
    url(r'^signup$', views.signup_page, name='signup'),
    url(r'^find$', views.find_page, name='find'),
    url(r'^profile$', views.profile_page, name='profile'),
    url(r'^physician$', views.physician_profile_page, name='physician_profile'),
    url(r'^account$', views.account_page, name='account'),

    url(r'^archive$', views.archive_page, name='archive'),
    # url(r'^archive/upload$', views.archive_upload_page, name='archive_upload'),
    url(r'^archive/upload$', views.ArchiveUploadView.as_view(), name='archive_upload'),
    # url(r'^archive/detail/(?P<image_id>[0-9]+)$', views.medical_image_page, name='archive_detail'),
    url(r'^archive/detail/(?P<image_id>[0-9]+)$', views.ArchiveDetailView.as_view(), name='archive_detail'),

    url(r'^interpretation$', views.patient_interpretation_list_page, name='interpretation'),
    url(r'^interpretation/request$', views.patient_request_list_page, name='interpretation_request_list'),
    url(r'^interpretation/request/detail/(?P<request_id>[0-9]+)$', views.patient_interpretation_request_detail_page, name='interpretation_request_detail'),
    url(r'^interpretation/(?P<intpr_id>[0-9]+)$', views.patient_interpretation_detail_page, name='interpretation_detail'),

    url(r'^interpretations$', views.physician_interpretation_page, name='physician_interpretation'),
    url(r'^interpretations/detail/(?P<intpr_id>[0-9]+)$', views.physician_interpretation_detail_page, name='physician_interpretation_detail'),
    url(r'^interpretations/response$', views.physician_interpretation_response_page, name='interpretation_response'),
    url(r'^interpretations/search$', views.physician_interpretation_search, name='interpretation_search'),
    url(r'^interpretations/search/detail/(?P<request_id>[0-9]+)$', views.physician_request_search_detail_page, name='interpretation_search_detail'),
    url(r'^interpretations/write/(?P<request_id>[0-9]+)$', views.physician_interpretation_write, name='interpretation_write'),

    # url(r'^opinion/(?P<opinion_id>[0-9]+)/$', views.opinion, name='opinion'),
    # url(r'^user/(?P<user_name>[ a-zA-Z_-]+)/$', views.user, name='user'),
    # url(r'^template$', views.template, name='template'),

    # url(r'^test$', views.test_page, name='test'),
    url(r'^test$', views.UploadViewTest.as_view(), name='test'),


    ### for APIs ###
    url(r'^api/sessions$', apis.handle_session_mgt),
    url(r'^api/intpr_session$', apis.handle_intpr_session_mgt),
    url(r'^api/user$', apis.handle_user_mgt),
    url(r'^api/patient_profile$', apis.handle_patient_profile_mgt),
    url(r'^api/physician_profile$', apis.handle_physician_profile_mgt),
    url(r'^api/medical_image$', apis.handle_medical_image_mgt),
    url(r'^api/interpretation$', apis.handle_interpretation_mgt),
    url(r'^api/analytics$', apis.handle_analytics_mgt),
    url(r'^api/payment$', apis.handle_payment_mgt),
    url(r'^api/get_upload_progress$', apis.handle_image_uploading_progress),
    url(r'^api/image_upload$', apis.handle_multple_image_upload),

    url(r'^api/archive$', apis.handle_archive),

    url(r'^api/test$', apis.handle_test),
    url(r'^json_res/success$', views.json_response_success),

    url(r'^auth/(?P<user_id>[-._a-z0-9]+)/(?P<auth_code>[a-zA-Z0-9]+)$', views.auth_email_page, name='auth_email'),
    url(r'^auth/update/(?P<user_id>[-._a-z0-9]+)/(?P<auth_code>[a-zA-Z0-9]+)$', views.auth_change_email_page, name='auth_email_update'),

    url(r'^', views.page_not_found_view)
]

miaas_server/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from miaas_server import settings

__author__ = 'hanter'


from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('miaas.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG and not urlpatterns:
    urlpatterns += staticfiles_urlpatterns()

miaas/forms.py
# Django Multiupload Required: pip install django-multiupload
from django import forms

from multiupload.fields import MultiFileField

class UploadForm(forms.Form):
    attachments = MultiFileField(min_num=1)
    # attachments = MultiFileField(min_num=1, max_num=3, max_file_size=1024*1024*5)


# References
# https://github.com/Chive/django-multiupload
# https://www.chicagodjango.com/blog/multiple-file-uploads-django/

miaas/views.py
from miaas import sample_contexts
from miaas.utils.utils import timestamp_to_date_string, get_interpretation_status
from django.http import Http404

__author__ = 'hanter'

from django.shortcuts import render, get_object_or_404, render_to_response, redirect
from django.template import RequestContext
from django.http import JsonResponse, HttpResponse, HttpResponseNotFound
from django.core.urlresolvers import reverse
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

from django.views.generic.edit import FormView
from .forms import UploadForm

from miaas import sample_contexts as sctx
from miaas import cloud_db, constants, cloud_db_copy, email_auth

from image_manager import ImageManager, ImageRetriever
import logging, json, time, copy
from pprint import pprint

# get db data -> 404 template, urls in tutorial #3: https://docs.djangoproject.com/en/1.9/intro/tutorial03/
# form, db class -> tutorial #4

#
# class IndexView(generic.ListView):
#     template_name = 'miaas/test.html'
#     context_object_name = 'latest_question_list'
#
#     def get_queryset(self):
#         """Return the last five published questions."""
#         return ['fdsdf', 'asdfew', 'earsdfc', '2dfa', 'asdq']

logging.basicConfig(
    format="[%(name)s][%(asctime)s] %(message)s",
    handlers=[logging.StreamHandler()],
    level=logging.INFO
)
logger = logging.getLogger(__name__)


def main2_page(request):
    context = _get_session_context(request)
    return render(request, 'miaas/main2.html', context)


def main_page(request):
    context = _get_session_context(request)
    # context = {
    #     'session': sctx.default_session,
    # }
    return render(request, 'miaas/main.html', context)


def index_page(request):
    context = _get_session_context(request)
    # context = {
    #     'session': sctx.default_session,
    # }
    return render(request, 'miaas/index.html', context)


# login reference: https://www.fir3net.com/Web-Development/Django/django.html
def signin_page(request):
    context = _get_session_context(request)
    return render(request, 'miaas/signin.html', context)

def auth_email_page(request, user_id, auth_code):
    context = {
        'user_id': user_id,
        'auth_code': auth_code
    }
    verified = email_auth.verify_auth_mail(user_id, auth_code)
    context['authenticated'] = verified

    return render(request, 'miaas/verify_auth_mail.html', context)

def auth_change_email_page(request, user_id, auth_code):
    context = {
        'user_id': user_id,
        'auth_code': auth_code
    }
    updated = email_auth.verify_and_update_auth_mail(user_id, auth_code)
    context['authenticated'] = updated

    return render(request, 'miaas/verify_change_mail.html', context)


def contact_us_page(request):
    return render(request, 'miaas/contact_us.html', None)


def signup_page(request):
    return render(request, 'miaas/signup.html', None)


def find_page(request):
    return render(request, 'miaas/find.html', None)


def account_page(request):
    db = cloud_db.DbManager()

    context = _get_session_context(request, pw_contains=True)
    return render(request, 'miaas/account.html', context)


def profile_page(request):
    context = _get_session_context(request)
    # logger.info(context)
    return render(request, 'miaas/patient_profile_v2.html', context)


def archive_upload_page(request):
    context = _get_session_context(request)
    return render(request, 'miaas/patient_medical_image_upload.html', context)


def physician_profile_page(request):
    context = _get_session_context(request)
    return render(request, 'miaas/physician_profile.html', context)


def _get_session_context(request, pw_contains=False):
    context = {}
    if 'user' in request.session.keys():
        context['user_session'] = copy.deepcopy(request.session['user'])
        if context.get('user_session') and not pw_contains:
            context['user_session'].pop('password', None)

    if 'intpr_session' in request.session.keys():
        context['intpr_session'] = request.session['intpr_session']

    # session expiry for 1 hour
    request.session.set_expiry(60*60)

    return context


####################
#  Details Pages #
####################

# patient
# def medical_image_page(request, image_id):
#     context = _get_session_context(request)
#     if request.GET.get('lastPage'):
#         context['lastPage'] = request.GET['lastPage']
#
#     if not image_id or int(image_id) < 0:
#         return archive_page(request)
#     else:
#         try:
#             db = cloud_db_copy.DbManager()
#             image, = db.retrieve_detail(db.PATIENT_IMAGE_DETAIL, image_id)
#             intpr_list = db.retrieve_list(db.IMAGE_INTPR_LIST, image_id)
#             if image['user_id'] != request.session.get('user'):
#                 return render(request, 'miaas/404.html', context="")
#             context['image'] = image
#             context['intpr_list'] = intpr_list
#         except Exception:
#             return render(request, 'miaas/404.html', context="")
#
#             # if result.get('image') and isinstance(result.get('intpr'), list):
#             #     context['image'] = result['image']
#             #     context['intpr_list'] = result['intpr']
#             # request.session['medical_image'][str(result['image']['image_id'])] = result['image']
#             # logger.info('image page(%s): %s' % (result['image']['image_id'], request.session['medical_image']))
#             # request.session['curr_image'] = result['image']
#     return render(request, 'miaas/patient_medical_image.html', context)


def patient_interpretation_detail_page(request, intpr_id):
    context = _get_session_context(request)
    if request.GET.get('lastPage'):
        context['lastPage'] = request.GET['lastPage']

    if not intpr_id or int(intpr_id) < 0:
        return patient_interpretation_list_page(request)
    if request.session.get('user'):
        try:
            db = cloud_db_copy.DbManager()
            intpr, physician, request_detail, image = db.retrieve_detail(db.PATIENT_INTPR_DETAIL, intpr_id)
            if image['patient_id'] != request.session['user']['user_id']:
                return render(request, 'miaas/404.html', context="")
            context['intpr'] = intpr
            context['physician'] = physician
            context['request_detail'] = request_detail
            context['image'] = image
        except Exception as e:
            # print e
            return render(request, 'miaas/404.html', context="")
    logger.info('interpretation_detail_page get: %s' % request.GET)
    return render(request, 'miaas/patient_interpretation_detail.html', context)


def patient_interpretation_request_detail_page(request, request_id):
    context = _get_session_context(request)
    if request.GET.get('lastPage'):
        context['lastPage'] = request.GET['lastPage']

    if not request_id or int(request_id) < 0:
        return patient_request_list_page(request)
    if request.session.get('user'):
        try:
            db = cloud_db_copy.DbManager()
            cdb = None
            request_detail, image = db.retrieve_detail(db.PATIENT_REQUEST_DETAIL, request_id)
            if image['patient_id'] != request.session['user']['user_id']:
                return patient_request_list_page(request)
            if request_detail['status'] == 0:
                cdb = cloud_db.DbManager()
                intpr_id = cdb.retrieve_interpretation_by_request_id(request_detail['request_id'])
                if intpr_id:
                    context['redirection'] = True
                    context['intpr_id'] = intpr_id
                else:
                    raise Exception()
            else:
                responses = db.retrieve_list(db.REQUEST_RESPONSE_LIST, request_detail['request_id'])
                context['image'] = image
                context['request_detail'] = request_detail
                context['responses'] = responses
        except Exception:
            return render(request, 'miaas/404.html', context="")
        finally:
            db.close()
            if cdb: cdb.close()
    logger.info('interpretation_request_detail_page get: %s' % request.GET)
    return render(request, 'miaas/patient_interpretation_request_detail.html', context)


# physician
def physician_request_search_detail_page(request, request_id):
    context = _get_session_context(request)
    if request.GET.get('lastPage'):
        context['lastPage'] = request.GET['lastPage']

    if not request_id or int(request_id) < 0:
        return physician_interpretation_search(request)
    if request.session.get('user'):
        try:
            db = cloud_db_copy.DbManager()
            request_detail, patient, image, intpr_temp = db.retrieve_detail(db.PHYSICIAN_REQUEST_DETAIL, request_id)
            if request_detail['status'] == 0:
                raise Exception()
            context['request_detail'] = request_detail
            context['patient'] = patient
            context['image'] = image
            # pprint(context)
        except Exception:
            return render(request, 'miaas/404.html', context="")

    logger.info('physician_request_search_detail_page get: %s' % request.GET)
    return render(request, 'miaas/physician_interpretation_search_detail.html', context)


def physician_interpretation_write(request, request_id):
    context = _get_session_context(request)
    if request.GET.get('lastPage'):
        context['lastPage'] = request.GET['lastPage']

    if not request_id or int(request_id) < 0:
        return physician_interpretation_response_page(request)
    if request.session.get('user'):
        try:
            db = cloud_db_copy.DbManager()
            cdb = None
            request_detail, patient, image, intpr_temp = db.retrieve_detail(db.PHYSICIAN_REQUEST_DETAIL, request_id)
            if request_detail['status'] == 0:

templates/miaas/json_code_success.html
{"code": "SUCCESS"}

templates/miaas/patient_archive.html
{% if not user_session or user_session.user_type != 'patient' %}
    <script type="text/javascript">
        location.replace({{ "'" }}{% url 'miaas:index' %}{{ "'" }});
    </script>
{% endif %}

{% load staticfiles %}
{% load my_filters %}

{% include 'miaas/template_header.html' %}
{% include 'miaas/template_nav_patient.html' %}
<!-- custom css -->
<link rel="stylesheet" type="text/css" href="{% static 'miass/data_table_css/dataTables.bootstrap.css' %}">


<div class="container">
    <section class="section section-default">
        <div class="row">
            <div class="col-xs-12 col-title">
                <h2 class="text-primary">Medical Image Archive</h2>
            </div>
            <div class="col-xs-12 col-table">
                {% if dt_list %}
                    <div class="table-container row">
                        <div class="table-title col-xs-12 col-md-4">Medical Image List</div>
                        <table id="dataTable" class="table table-striped table-bordered table-hover display"
                               width="100%"></table>
                        {% else %}

                        <div class="table-nodata">
                            <h4 class="text-danger">There is no Medical Images</h4>
                            <p>You can upload your FIRST medical image</p>
                            <a class="btn btn-primary" href="{% url 'miaas:archive_upload' %}" type="button">Upload</a>
                        </div>
                    </div>
                {% endif %}
            </div>
            {% if dt_list %}
                <div class="col-xs-12 col-md-4 col-md-offset-4">
                    <a class="btn btn-primary btn-lg btn-block"
                       href="{% url 'miaas:archive_upload' %}" type="button">Upload Image</a>
                </div>
            {% endif %}
        </div>
    </section>
</div>


{% include 'miaas/template_footer.html' %}


<script src="{% static 'miass/data_table_js/jquery.dataTables.js' %}"></script>
<script src="{% static 'miass/data_table_js/dataTables.bootstrap.js' %}"></script>
<!-- custom javascript -->
<script>
    {% if dt_list %}
        var dataSet = {{ dt_list |  safe }};
        var pageFirstDraw = true;

        $(document).ready(function () {
            $.LoadingOverlay('show');
            var table = $('#dataTable')
                    .DataTable({
                        "fnInitComplete": function(oSettings, json){
                            $.LoadingOverlay('hide');
                        },
                        data: dataSet,
                        order: [[0, "desc"]],
                        columns: [
                            {
                                title: "Upload Date",
                                render: {
                                    "display": function (data) {
                                        var date = new Date(data);
                                        var year = date.getFullYear();
                                        var month = (1 + date.getMonth()).toString();
                                        month = month.length > 1 ? month : '0' + month;
                                        var day = date.getDate().toString();
                                        day = day.length > 1 ? day : '0' + day;
                                        return (month + '/' + day + '/' + year.toString().substr(2))
                                    }
                                }
                            },
                            {title: "Image Subject"},
                            {title: "Image Type"},
                            {
                                title: "Recorded Date",
                                render: {
                                    "display": function (data) {
                                        var date = new Date(data);
                                        var year = date.getFullYear();
                                        var month = (1 + date.getMonth()).toString();
                                        month = month.length > 1 ? month : '0' + month;
                                        var day = date.getDate().toString();
                                        day = day.length > 1 ? day : '0' + day;
                                        return (month + '/' + day + '/' + year.toString().substr(2))
                                    }
                                }
                            },
                            {title: "Interpretation Count"}
                        ]
                    });
            table.afnSortData = function (osSettings, iColumn) {
                var aData = [];
            };

            {% if page %}
                table.page(parseInt({{ page }})-1).draw('page');
            {% endif %}

            $('#dataTable tbody').on('click', 'tr', function () {
                $.LoadingOverlay('show');
                var data = table.row(this).data();
                var index_id = data[data.length - 1];
                var nowPage = table.page.info()["page"]+1;
                location.href = '{% url 'miaas:archive' %}/detail/' + index_id + '?lastPage=' + nowPage;
            });
        });

    {% endif %}

</script>

</body>
</html>

templates/miaas/template_nav_physician.html
{% load staticfiles %}
{% load my_filters %}
</head>

<body>
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container nav-container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collasped"
                    data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand onloading" href="{% url 'miaas:index' %}">MIAAS</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a id="nav_physician_profile" class="onloading" href="{% url 'miaas:physician_profile' %}">Physician
                    Profile</a></li>
                <li class="dropdown">
                    <a id="nav_interpretations" href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                       aria-haspopup="true"
                       aria-expanded="false">Interpretations
                        <span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="onloading" href="{% url 'miaas:interpretation_response' %}">Respond Requests</a>
                        </li>
                        <li><a class="onloading" href="{% url 'miaas:physician_interpretation' %}">My
                            Interpretations</a></li>
                        <li><a class="onloading" href="{% url 'miaas:interpretation_search' %}">Search Requests</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown notify-dropdown">
                    <a class="dropdown notify-dropdown hidden-xs" role="button">
                        <div id='bell'>
                            <i class="glyphicon glyphicon-bell"
                                    {% if intpr_session.new == 0 %}
                               style="color: #777777"
                                    {% endif %}
                            ></i>
                        </div>
                    </a>
                    <ul class="dropdown-menu notifications hidden-xs" role="menu">
                        <div class="notification-heading">
                            <h4 class="menu-title">Notifications</h4>
                        </div>
                        <li class="divider"></li>
                        <div id='notifications-wrapper' class="notifications-wrapper">
                            {% if intpr_session.sessions %}
                                {% for session in intpr_session.sessions %}
                                    {% if session.type == 'cancel' %}
                                        <div class="content" href="#">
                                            {% if session.status == 0 %}
                                                <div class="alert alert-custom-new fade in"
                                                     session_id= {{ session.session_id }}>
                                                    <a href="#" class="close" data-dismiss="alert"
                                                       aria-label="close" session_id= {{ session.session_id }}>&times;</a>
                                                    <h4 class="item-title">CANCEL
                                                        <span class="item-time">{{ session.timestamp|datetime_string }}</span>
                                                    </h4>
                                                    <p class="item-info"> The interpretation request,
                                                        "<span class="item-link">{{ session.value.request_subject| less_string:40 }}</span>", was canceled.</p>
                                                </div>
                                            {% elif session.status == 1 %}
                                                <div class="alert alert-custom fade in"
                                                     session_id= {{ session.session_id }}>
                                                    <a href="#" class="close" data-dismiss="alert"
                                                       aria-label="close" session_id= {{ session.session_id }}>&times;</a>
                                                    <h4 class="item-title">CANCEL
                                                        <span class="item-time">{{ session.timestamp|datetime_string }}</span>
                                                    </h4>
                                                    <p class="item-info"> The interpretation request,
                                                        "<span class="item-link">{{ session.value.request_subject| less_string:40 }}</span>", was canceled.</p>
                                                </div>
                                            {% endif %}
                                        </div>
                                    {% elif session.type == 'select' %}
                                        <div class="content" href="#">
                                            {% if session.status == 0 %}
                                                <div class="alert alert-custom-new fade in"
                                                     session_id= {{ session.session_id }}>
                                                    <a href="#" class="close" data-dismiss="alert"
                                                       aria-label="close" session_id= {{ session.session_id }}>&times;</a>
                                                    <h4 class="item-title">SELECT
                                                        <span class="item-time">{{ session.timestamp|datetime_string }}</span>
                                                    </h4>
                                                    <p class="item-info"> The patient, <strong>{{ session.name }}</strong>,
                                                        selected you to get interpretation for the request,
                                                        "<a class="item-link" href="{% url 'miaas:physician_interpretation' %}/write/{{ session.value.request_id }}">{{ session.value.request_subject | less_string:40 }}</a>".
                                                    </p>
                                                </div>
                                            {% elif session.status == 1 %}
                                                <div class="alert alert-custom fade in"
                                                     session_id= {{ session.session_id }}>
                                                    <a href="#" class="close" data-dismiss="alert"
                                                       aria-label="close" session_id= {{ session.session_id }}>&times;</a>
                                                    <h4 class="item-title">SELECT
                                                        <span class="item-time">{{ session.timestamp|datetime_string }}</span>
                                                    </h4>
                                                    <p class="item-info"> The patient, <strong>{{ session.name }}</strong>,
                                                        selected you to get interpretation for the request,
                                                        "<a class="item-link" href="{% url 'miaas:physician_interpretation' %}/write/{{ session.value.request_id }}">{{ session.value.request_subject | less_string:40 }}</a>".
                                                    </p>
                                                </div>
                                            {% endif %}
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            {% else %}
                                <h3></h3>
                            {% endif %}

                        </div>
                        <li class="divider"></li>
                        <div id="btnRefresh" class="btn btn-primary col-xs-offset-4 col-xs-4">Refresh</div>
                    </ul>
                </li>

                <li class="dropdown">
                    <a id="nav_account" href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                       aria-haspopup="true"
                       aria-expanded="false"><span id="navbar-logined-text">
                        <span>Hi, Dr. {{ user_session.name }} </span></span><span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="onloading" href="{% url 'miaas:account' %}">Account Setting</a></li>
                        <li><a href="#" onclick="signout()">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- scripts -->
<script>
    var intpr_session = '{{ intpr_session }}';
    var userId = '{{ user_session.user_id }}';
    var userType = '{{ user_session.user_type }}';
</script>

templates/miaas/verify_change_mail.html
{% load staticfiles %}
{% load my_filters %}

{% include 'miaas/template_header.html' %}

<!-- custom css -->
<link rel="stylesheet" type="text/css" href="{% static 'miass/css/verify_auth_mail.css' %}">

<body>

{% if authenticated %}
<div class="container">
    <section class="section section-auth-confirm">
        <div class="div-auth-confirm">
            <div class="row row-auth-title">
                <div class="col-xs-12">
                    <h2 class="text-primary">MIAAS Email Authentication</h2>
                </div>
            </div>
            <div class="row row-auth-content">
                <div class="col-xs-12" id="col-signup-usertype">
                    <br/>
                    <h4>{{ user_id }}, your email is successfully changed.</h4>
                    <br/>
                    <a href="{% url 'miaas:index' %}" class="btn btn-lg btn-primary btn-block">Go to MIIAS</a>
                </div>
            </div>
        </div>
    </section>
</div>

{% else %}

<div class="container">
    <section class="section section-auth-confirm">
        <div class="div-auth-confirm">
            <div class="row row-auth-title">
                <div class="col-xs-12">
                    <h2 class="text-primary">MIAAS Email Authentication</h2>
                </div>
            </div>
            <div class="row row-auth-content">
                <div class="col-xs-12" id="col-signup-usertype">
                    <br/>
                    <h4>Invalid Authentication Link</h4>
                    <h5>Please check your email is latest. If not, please request to resend authentication email.</h5>
                    <br/>
                    <a href="javascript: history.back();" type="button" class="btn btn-lg btn-primary btn-block">Back</a>
                </div>
            </div>
        </div>
    </section>
</div>

{% endif %}

{% include 'miaas/template_footer.html' %}

</body>
</html>